services:
  - type: web
    name: stock-predictor
    env: python
    # build-time only: install deps
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    # at runtime we just launch Streamlit
    startCommand: streamlit run app.py \
      --server.port=$PORT \
      --server.enableXsrfProtection=false
    plan: free
